export default {
  RECEIVE_PRODUCT_TYPES: 'RECEIVE_PRODUCT_TYPES',
  RECEIVE_PRODUCT_LIST: 'RECEIVE_PRODUCT_LIST',
  RECEIVE_COLLECT_LIST: 'RECEIVE_COLLECT_LIST',
  RECEIVE_ORDER_LIST: 'RECEIVE_ORDER_LIST',
  RECEIVE_PRODUCT_DETAIL: 'RECEIVE_PRODUCT_DETAIL',
  RECEIVE_MESSAGE_LIST: 'RECEIVE_MESSAGE_LIST',
  RECEIVE_SEARCH_LIST: 'RECEIVE_SEARCH_LIST'
}